### ISSUE TITLE
Handle errors when making bad calls

### ISSUE THREAD

**Issue by foggy1** [ex-aws/ex_aws_cloudwatch#14]
## System info

Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.2 (compiled with Erlang/OTP 21)
* ex_aws 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ex_aws) 8df2f96f
* ex_aws_dynamo 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_dynamo) fd472900
* ex_aws_sqs 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_sqs) ead66c34
* ex_aws_cloudwatch 2.0.3 (git@github.com:VodyTV/ex_aws_cloudwatch.git) (mix)
* httpoison 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (httpoison) e0b3c2ad

## Issue

Say I run the following code:

`ExAws.Cloudwatch.put_metric_data([%{this_is_a_number: 3}], "this is a test") |> ExAws.request`

Since I didn't include "metric_name" and "value" in my map, this call is invalid. However, instead of spitting out an `{:error, reason}` tuple, I get the following:

```
** (UndefinedFunctionError) function Poison.decode/1 is undefined (module Poison is not available)
    Poison.decode("<ErrorResponse xmlns=\"http://monitoring.amazonaws.com/doc/2010-08-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>InvalidParameterCombination</Code>\n    <Message>At least one of the parameters must be specified.</Message>\n  </Error>\n  <RequestId>$REQUEST_ID</RequestId>\n</ErrorResponse>\n")
    (ex_aws) lib/ex_aws/request.ex:58: ExAws.Request.client_error/2
    (ex_aws) lib/ex_aws/request.ex:42: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/query.ex:33: ExAws.Operation.ExAws.Operation.Query.perform/2
```
As you can see, this is XML: Poison has no business trying to decode this. Additionally, the request should not have even bubbled up to ExAws.request: it should be handled by the present client and spit back an error message in an error tuple as is convention.

I'm happy to help with this if someone can point me to some relevant code or if I get some extra time on my hands.

**Comment by foggy1** [comment]
This was my fault, I was breaking all my config by adding an additional `:app` symbol at the end of the config line as you can see above (I was also doing this with the root :ex_aws dep
